# -*- coding: utf-8 -*-
"""DV Week - 07

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nkiEwGiU7gmCk0DK5N6vuJ2WKhN6cG_V
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/StudentsPerformance.csv")

df

df.head()

df.tail()

df.describe()

df.shape

df.info()

df.isnull().sum()

df.duplicated().sum()

score_columns = ['math score','reading score','writing score']

score_columns

df[score_columns].describe()

df[score_columns].quantile(0.25)

df["Total Score"] = (df["math score"]
                     + df["reading score"]
                     + df["writing score"])

df.columns

df["Percentage"] = (df["Total Score"]/300)*100

df[["Total Score","Percentage"]].head()

Q1 = df['math score'].quantile(0.25)
Q3 = df['math score'].quantile(0.75)
IQR = Q3 - Q1
outliers = df[(df['math score'] < (Q1 - 1.5 * IQR)) | (df['math score'] > (Q3 + 1.5 * IQR))]
print(f"Number of outliers in math score: {len(outliers)}")