# -*- coding: utf-8 -*-
"""DV Week - 06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wq-cFW_h7e3iX89dM326ziZApjzFnmN4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/healthcare_dataset.csv")

print("Original Data:")
print(df.head())

print(df.shape)

print(df.describe())

df = df.dropna()

print("\nMissing Values:")
print(df.isnull().sum())

df["Date of Admission"] = pd.to_datetime(
    df["Date of Admission"]
)

df["Discharge Date"] = pd.to_datetime(
    df["Discharge Date"]
)

print("\nStandardized Dates:")
print(df[["Date of Admission", "Discharge Date"]].head())

df["Urgency"] = df["Admission Type"].map({
    "Emergency": "Emergency",
    "Elective": "Elective",
    "Urgent": "Urgent"
})

print("\nAdmission Urgency:")
print(df[["Admission Type", "Urgency"]].head())

df["Stay_Days"] = (
    df["Discharge Date"] - df["Date of Admission"]
).dt.days

print("\nBilling Amount Statistics:")
print(df["Billing Amount"].describe())

print("\nHospital Stay Statistics:")
print(df["Stay_Days"].describe())

demographics = df.groupby(
    "Medical Condition"
)["Age"].agg(["count", "mean"])

print("\nDemographics by Medical Condition:")
print(demographics)

gender_distribution = pd.crosstab(
    df["Medical Condition"],
    df["Gender"]
)

print("\nGender Distribution by Medical Condition:")
print(gender_distribution)

plt.figure(figsize=(8, 5))

sns.countplot(
    data=df,
    x="Medical Condition"
)

plt.title("Patients by Medical Condition")
plt.xlabel("Medical Condition")
plt.ylabel("Number of Patients")
plt.xticks(rotation=45)

plt.show()

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="Medical Condition",
    y="Billing Amount"
)

plt.title("Billing Amount by Medical Condition")
plt.xlabel("Medical Condition")
plt.ylabel("Billing Amount")
plt.xticks(rotation=45)

plt.show()